#!/bin/bash
## Required PBS Directives --------------------------------------
#PBS -A ERDCV00898M20
#PBS -q standard_sm
#PBS -l select=1:ncpus=44:mpiprocs=44
#PBS -l walltime=12:00:00
#PBS -l application=s2g
#PBS -j oe
#PBS -M fyshi@udel.edu
#PBS -m be
#PBS -N s2g

## Execution Block ----------------------------------------------
# Environment Setup
FUNWAVE=${HOME}/USERS_APP/SUBSURFACE/SUBGRID
EXEC=${FUNWAVE}/src/flood_coupling_maxgrn

INPUT=${PBS_O_WORKDIR}
BATHY=${PBS_O_WORKDIR}

# cd to your scratch directory in /work
RUNDIR=${WORKDIR}/Subgrid_storm_manning
mkdir -p ${RUNDIR}
mkdir -p ${RUNDIR}/output

cd ${RUNDIR}


## Launching -----------------------------------------------------
# copy desired/needed files and run the job
cp ${INPUT}/input_storm_p03_ka001_manning.txt ${RUNDIR}/input.txt
cp ${INPUT}/bkm_bc_coarse.txt ${RUNDIR}/.
cp ${INPUT}/station_subgrid_groundwater.txt ${RUNDIR}/station.txt
cp ${INPUT}/bkm_dep.txt ${RUNDIR}/.
cp ${INPUT}/manning_coarse_max0p05_G.txt ${RUNDIR}/manning.txt
# The following two lines provide an example of setting up and running 
# a CRAY MPICH parallel code  built with the INTEL compiler.
module swap PrgEnv-cray PrgEnv-intel
aprun -n 40 ${EXEC}
